

spring:
  mvc:
    view:
      prefix: html/

    static-path-pattern: /**
  resources:
    static-locations: classpath:/
  application:
    name: demo
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    name: sanqiu
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/chuang_qian?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    encoding: UTF-8
    basename: i18n/abt_messages
    use-code-as-default-message: true

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0






server:
  servlet:
    session:
      timeout: 2592000

mybatis:
  mapper-locations: ["classpath*:mapper/**/*.xml"]
  type-aliases-package: com.ysq.theTourGuide.mapper

logging:
  level:
    com.ysq.chuang_qian.mapper: DEBUG



